networks:
  app-network:
    driver: bridge

volumes:
  sql_server_data:
    driver: local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
      - "8084:8084"
    environment:
      DB_SERVER: db  # The name of the database container (the "db" service)
      DB_PORT: 1433
      DB_NAME: master
      DB_USER: sa  # Using the SQL Server 'sa' user
      DB_PASSWORD: adm123 # The same password used for the sa user
    networks:
      - app-network
    depends_on:
      - meli_geolocation
  meli_geolocation:
    container_name: mssql-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - app-network
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=adm123  # Strong password for the SQL Server sa account
      - MSSQL_PID=Express
    restart: always
    volumes:
      - ./sql-server-data:/var/opt/mssql
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets